name: Build and Sign Web Extension

on:
  release:
    types: [published]

jobs:
  build-and-sign:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: "yarn"
        cache-dependency-path: yarn.lock

    - name: Install dependencies
      run: yarn install

    - name: Install jq if not already installed
      run: |
        if ! command -v jq &> /dev/null; then
          sudo apt-get update && sudo apt-get install -y jq
        fi

    - name: Extract version from release tag
      id: extract_version
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Update manifest.json with version
      run: |
        jq --arg version "$RELEASE_VERSION" '.version = $version' manifest.json > manifest.tmp.json
        mv manifest.tmp.json manifest.json

    - name: Build the project
      run: yarn build

    - name: Install web-ext
      run: yarn global add web-ext

    - name: Build the extension
      run: web-ext build

    - name: Sign the extension
      env:
        WEB_EXT_API_KEY: ${{ secrets.WEB_EXT_API_KEY }}
        WEB_EXT_API_SECRET: ${{ secrets.WEB_EXT_API_SECRET }}
      run: web-ext sign --channel=unlisted --api-key=$WEB_EXT_API_KEY --api-secret=$WEB_EXT_API_SECRET

    - name: Rename signed extension
      run: mv web-ext-artifacts/*.xpi web-ext-artifacts/sindicator@the-guardian-com.xpi

    - name: Upload signed extension
      uses: actions/upload-artifact@v4
      with:
        name: sindicator-signed-extension
        path: web-ext-artifacts/*.xpi